In [20]:
import numpy as np
array1 = np.array([
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4],
    [1,2,3,4]
])
print(array1[:,:3])
array2 = np.zeros_like(array1[:,1],dtype=int)
print(array2)
array2 = np.expand_dims(array2,axis=1)
print(array2.shape)
print(array2)


[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[0 0 0 0]
(4, 1)
[[0]
 [0]
 [0]
 [0]]


In [4]:
arr2 = np.array(range(1,8),(2,4))
print(arr2)

TypeError: Cannot interpret '2' as a data type

In [6]:
import numpy as np
a = np.random.randint(0,10,size=(3,4))
print(a)
a = np.vstack((a,[0,0,0,1]))
print(a)

[[0 1 1 6]
 [1 6 7 2]
 [0 9 6 6]]
[[0 1 1 6]
 [1 6 7 2]
 [0 9 6 6]
 [0 0 0 1]]


In [16]:
import numpy as np
a = np.random.randint(0,10,size=(3,2,3))
print(a)
b = np.random.randint(0,10,size=(3,2))
print(b)
#expand dimensions
b = np.expand_dims(b,axis=2)
print(b.shape)
print(b)
#concatenate a and b
c = np.concatenate((a,b),axis=2)
print(c)
#or 

[[[8 4 1]
  [6 5 2]]

 [[1 4 2]
  [9 0 7]]

 [[7 0 7]
  [7 4 5]]]
[[6 5]
 [8 5]
 [6 7]]
(3, 2, 1)
[[[6]
  [5]]

 [[8]
  [5]]

 [[6]
  [7]]]
[[[8 4 1 6]
  [6 5 2 5]]

 [[1 4 2 8]
  [9 0 7 5]]

 [[7 0 7 6]
  [7 4 5 7]]]


In [30]:
import numpy as np
a = np.random.randint(0,10,size=(1,1))
print(a)
a = np.squeeze(a)
print(type(a))
b = np.float32(a)
print(type(b))

[[5]]
<class 'numpy.ndarray'>
<class 'numpy.float32'>


In [15]:
import numpy as np
a = np.load("/sharedata/home/shared/hanxiao/kitti/dataset/sequences/02/residual_order_points_1/004660.npy")
print(a.shape)
print(a[1110][0])
b = np.load("/sharedata/home/shared/hanxiao/kitti/dataset/sequences/01/residual_points_1/000001.npy")
print(b[10][1000])
c = np.fromfile("/sharedata/home/shared/hanxiao/kitti/dataset/sequences/00/residual_points_1/000001.npy",dtype=np.float32)
print(c.shape)

(126308, 1)
0.0
[24.981855    1.8391209  -0.7627692   0.02619311]
(524320,)


In [26]:
import numpy as np
a = np.random.randint(0,10,size=(2,4))
print(a)
b = a[:,:3]
print(b)
print(b.shape)
depth = np.linalg.norm(b[:, :3].reshape((-1,3)), 2, axis=1)
print(depth)

[[3 5 3 8]
 [3 8 1 1]]
[[3 5 3]
 [3 8 1]]
(2, 3)
[6.55743852 8.60232527]


In [28]:
import numpy as np
a = np.random.randint(0,10,size=(20,3))
print(a)
depth = np.linalg.norm(a[:, :3], 2, axis=1)
print(depth)
min_range = 7
max_range = 12
b = a[(depth > min_range) & (depth < max_range)]
print(b)

[[6 7 7]
 [4 1 3]
 [8 6 5]
 [8 2 6]
 [4 9 2]
 [2 5 3]
 [5 6 2]
 [7 2 8]
 [4 7 5]
 [2 7 7]
 [6 1 8]
 [2 9 2]
 [3 6 4]
 [4 2 9]
 [8 8 2]
 [0 7 3]
 [9 9 1]
 [0 9 5]
 [6 5 6]
 [6 8 4]]
[11.5758369   5.09901951 11.18033989 10.19803903 10.04987562  6.164414
  8.06225775 10.81665383  9.48683298 10.09950494 10.04987562  9.43398113
  7.81024968 10.04987562 11.48912529  7.61577311 12.76714533 10.29563014
  9.8488578  10.77032961]
[[6 7 7]
 [8 6 5]
 [8 2 6]
 [4 9 2]
 [5 6 2]
 [7 2 8]
 [4 7 5]
 [2 7 7]
 [6 1 8]
 [2 9 2]
 [3 6 4]
 [4 2 9]
 [8 8 2]
 [0 7 3]
 [0 9 5]
 [6 5 6]
 [6 8 4]]


In [35]:
import numpy as np
a = np.empty((64,2024,4))
print(a[100][2000][3])

IndexError: index 100 is out of bounds for axis 0 with size 64